spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    hikari:
      pool-name: mysql/ds1
      connection-timeout: 45000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
      minimum-idle: 0
      connection-test-query: "select 1"
      validation-timeout: 1000
      isolate-internal-queries: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/squirrel
      username: root
      password: root

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
